//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.DBServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractOrder
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public Nullable<System.Guid> ContractMakeUserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public Nullable<int> Flag { get; set; }
        public System.Guid UserId { get; set; }
    }
}
