//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.DBServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntentionOrder
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> IntentionReceiveUserId { get; set; }
        public Nullable<System.Guid> FinalRecordUserId { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public string ReceiveRemarks { get; set; }
        public Nullable<System.DateTime> FinalRecordTime { get; set; }
        public string FinalRecordRemarks { get; set; }
        public Nullable<int> Flag { get; set; }
        public System.Guid IntentionUserId { get; set; }
    }
}
