//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.DBServer.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LS_ZhaoFaEntities : DbContext
    {
        public LS_ZhaoFaEntities()
            : base("name=LS_ZhaoFaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserMemorandum> UserMemorandum { get; set; }
        public virtual DbSet<UserSuggestion> UserSuggestion { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<UserLogistics> UserLogistics { get; set; }
        public virtual DbSet<UserOrder> UserOrder { get; set; }
        public virtual DbSet<InquiryProductImg> InquiryProductImg { get; set; }
        public virtual DbSet<QuotationProduct> QuotationProduct { get; set; }
        public virtual DbSet<QuotationProductImg> QuotationProductImg { get; set; }
        public virtual DbSet<ShowPosition> ShowPosition { get; set; }
        public virtual DbSet<SoftWenInfo> SoftWenInfo { get; set; }
        public virtual DbSet<RedPackage> RedPackage { get; set; }
        public virtual DbSet<UserCoupon> UserCoupon { get; set; }
        public virtual DbSet<InquiryOrder> InquiryOrder { get; set; }
        public virtual DbSet<ContractOrder> ContractOrder { get; set; }
        public virtual DbSet<ContractProduct> ContractProduct { get; set; }
        public virtual DbSet<IntentionOrder> IntentionOrder { get; set; }
        public virtual DbSet<IntentionProduct> IntentionProduct { get; set; }
        public virtual DbSet<QuotationOrder> QuotationOrder { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
    }
}
