//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.DBServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid Id { get; set; }
        public string UserAccount { get; set; }
        public string UserPassWord { get; set; }
        public string UserName { get; set; }
        public int UserLv { get; set; }
        public string UserImg { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CompanyName { get; set; }
        public int Flag { get; set; }
    }
}
