//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.DBServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogistics
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public string DetailedInformation { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LogisticsTime { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> AdminId { get; set; }
        public System.Guid CountermanId { get; set; }
    }
}
