//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.DBServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal RealisticPrice { get; set; }
        public Nullable<System.Guid> CouponId { get; set; }
        public int Flag { get; set; }
        public int PayFlag { get; set; }
        public Nullable<System.Guid> AdminId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> SubmissionTime { get; set; }
        public Nullable<System.DateTime> PayingTime { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CurrentStateTime { get; set; }
        public string BusinessOrderId { get; set; }
        public string ProvinceAddress { get; set; }
        public string CityAddress { get; set; }
        public string DetailedAddress { get; set; }
    }
}
